### ISSUE TITLE
Reorganize Metadata Endpoints

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-openapi#30]
One of the reasons for not having separated metadata was due to previous account restrictions endpoint structure.

> Taking into consideration similar features that depend on others (restrictions, multisig), we are creating endpoints under each main independent concept (e.g. /account/<:accountId>/restrictons).

#28 changes the ``/restrictions`` endpoints and opens the door to reorganize metadata endpoints. 

## Proposal

The does not change the number of endpoints or responses, but how they are called. Repeat changing ``/account/{accountId}`` for mosaic and namespaces endpoints.

| Previous Endpoint | New endpoint |
|---------------------| -----------------|
| /account/{accountId}/metadata/ | /metadata/account/{accountId}|
| /account/{accountId}/metadata/{key} | /metadata/account/{accountId}/key/{key} |
| /account/{accountId}/metadata/{key}/sender/{publicKey} | /metadata/account/{accountId}/key/{key}/sender/{publicKey} |

@Vektrat @rg911 @fboucquez Let me know if do you have any objection/improvements.

**Comment by fboucquez** [comment]
Hi @dgarcia360, I have no problem with the endpoint change. Because the change is just the URLs, not where the methods are located (there is a metadata route already), I just need to regenerate my java clients. I don't need any code change. :)

**Comment by Vektrat** [comment]
makes sense to me

**Comment by rg911** [comment]
new endpoints look spot on
