### ISSUE TITLE
HaskLockTranscation mosaic object vs mosaicId/Value 

### ISSUE THREAD

**Issue by fboucquez** [nemtech/nem2-openapi#37]
Hi @dgarcia360 , 

I'm doing some integration tests and I noticed that the HaskLockTranscation returned by rest doesn't have the format defined in the open API spec. The rest payload doesn't have the nested mosaic object, it just has the mosaicId and the amount. Is this an open API issue or a rest issue? @Vektrat?

I think at this stage is easier to fix the open API than rest and TS SDK (@rg911). Please notice that Java SDK uses the object generated from the open API spec. I would need to patch the open API spec in order to fix the Java SDK.

https://github.com/nemtech/nem2-openapi/blob/master/spec/openapi3.yaml#L2287

![image](https://user-images.githubusercontent.com/5390558/66430993-75083700-ea1b-11e9-9f98-47b02cbab563.png)

![image](https://user-images.githubusercontent.com/5390558/66431013-7c2f4500-ea1b-11e9-940e-f4ffeeaa5f86.png)

![image](https://user-images.githubusercontent.com/5390558/66431019-7e919f00-ea1b-11e9-8f99-e0bdd627ff2f.png)

**Comment by fboucquez** [comment]
I've just patched the open API spec for Java.

```
    HashLockTransactionBodyDTO:
      type: object
      required:
        - mosaicId
        - amount
        - duration
        - hash
      properties:
        mosaicId:
          $ref: "#/components/schemas/MosaicId"
        amount:
          $ref: "#/components/schemas/Amount"
        duration:
          $ref: "#/components/schemas/BlockDuration"
        hash:
          $ref: "#/components/schemas/Hash256"
```

**Comment by Vektrat** [comment]
it's an openapi issue, afaik we have not modified this ever in rest, and rest structure always takes precedence over what the openapi says - openapi was/is made after rest, so probably a bug here

**Comment by dgarcia360** [comment]
Fixed here https://github.com/nemtech/nem2-openapi/pull/39, note that:

mosaicId:
          $ref: "#/components/schemas/**Unresolved**MosaicId"
