### ISSUE TITLE
Metadata valueSize not provided/not needed

### ISSUE THREAD

**Issue by fboucquez** [nemtech/nem2-openapi#38]
Hi @dgarcia360 

Open API specifies that the valueSize should be present in  Account/Mosaic/Namespace metadata transactions, for example:

https://github.com/nemtech/nem2-openapi/blob/master/spec/openapi3.yaml#L2649

It seems like Rest is not providing the valueSize anymore (@Vektrat ):

![image](https://user-images.githubusercontent.com/5390558/66433545-d4b51100-ea20-11e9-9417-1268b7a2b0bb.png)

valueSize is not required by catbuffer but it used to be provided in the rest transaction payloads. Is this valueSize required? Do we need it to calculate the new delta when updating metadata or can we just remove it from the open API spec? @rg911?

**Comment by Vektrat** [comment]
i copied the same behaviour as the message/messageSize from the transfer transaction, which was originally done like so by the core devs, if needed we can add it back

**Comment by dgarcia360** [comment]
Not needed, solved here https://github.com/nemtech/nem2-openapi/pull/40
